POST http://localhost:8080/users
content-type: application/json

{
  "test": "test"
}

###

POST https://class-manager-backend-tau.vercel.app/api/index/users
content-type: application/json

{
  "test": "test"
}
